services:
  rabbitmq1:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq1-data:/var/lib/rabbitmq
      - rabbitmq1-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq2:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq2-data:/var/lib/rabbitmq
      - rabbitmq2-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq3:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq3-data:/var/lib/rabbitmq
      - rabbitmq3-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  haproxy:
    image: haproxy:3.0
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs:
